### ISSUE TITLE
Unable to release jvm projects with Gradle >= 4.9

### ISSUE THREAD

**Issue by tobiasheine** [novoda/bintray-release#220]
When applying the plugin to a project that uses Gradle 4.9 or a newer version, the bintray release is failing.

From the logs:

```
Could not upload to 'https://api.bintray.com/content/novoda/snapshots/gradle-static-analysis-plugin/SNAPSHOT-14/property(class java/lang/String, fixed(class java/lang/String, com/novoda))/property(class java.lang.String, fixed(class java.lang.String, gradle-static-analysis-plugin))/property(class java.lang.String, fixed(class java.lang.String, SNAPSHOT-14))/property(class java.lang.String, fixed(class java.lang.String, gradle-static-analysis-plugin))-property(class java.lang.String, fixed(class java.lang.String, SNAPSHOT-14)).pom': HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'property(class java/lang/String, fixed(class java/lang/String, com/novoda))/property(class java.lang.String, fixed(class java.lang.String, gradle-static-analysis-plugin))/property(class java.lang.String, fixed(class java.lang.String, SNAPSHOT-14))/property(class java.lang.String, fixed(class java.lang.String, gradle-static-analysis-plugin))-property(class java.lang.String, fixed(class java.lang.String, SNAPSHOT-14)).pom'
```

**Comment by StefMa** [comment]
Known issue. See #177.
Alternatively you could try this plugin https://github.com/StefMa/bintray-release

**Comment by mr-archano** [comment]
@StefMa this is a different issue: the project is configured just fine, the upload tasks to Bintray seem to have some issue with their input (the artifacts to upload).

**Comment by tobiasheine** [comment]
I did some research and figured out it's a [bug](https://github.com/bintray/gradle-bintray-plugin/issues/253) on the jfrog bintray plugin.

**Comment by afollestad** [comment]
+1

**Comment by razerdp** [comment]
+2 need fix

**Comment by mr-archano** [comment]
@razerdp @afollestad feel free to let the maintainers of the jfrog plugin that is something you would like to get fixed asap. There's an issue opened here: https://github.com/bintray/gradle-bintray-plugin/issues/253

**Comment by afollestad** [comment]
The plugin doesn't work with >= 4.6 either

**Comment by qazhuhuihao** [comment]
+1 doesn't work with >= 4.6 either

**Comment by afollestad** [comment]
I know - I've commented on that one as well.

**Comment by mr-archano** [comment]
Well @afollestad, you can recognise how the issue is different, as the stacktrace in #177 is different from the log posted in the issue.

A superficial investigation can make you realise that #177 is a problem of this plugin related to Android library publication (because of a wrong usage of a private Gradle API), while this issue describes a problem affecting also plain java projects, as there is some problem in the underlying jfrog plugin (see https://github.com/bintray/gradle-bintray-plugin/issues/253)

**Comment by yhyzgn** [comment]
+1 The plugin doesn't work with >= 4.6 either

**Comment by mr-archano** [comment]
I renamed the issue as I see people are not taking the time to actually read the conversation and understand that this is not an Android-related problem (already tracked by #177). I hope this will help to avoid confusion going forward.

**Comment by mr-archano** [comment]
Fixed in release `0.9`

**Comment by ogrebgr** [comment]
The problem seems that is still present. I am bumping into it with plugin ver 0.9.2, gradle 4.10.3 (and 4.9).
It seems that it is caused by using older version of bintray-release plugin.
